In [746]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
excel_file = 'path/to/your/file.xlsx'

# Read all sheets into a dictionary of dataframes
dfs = pd.read_excel(excel_file, sheet_name=None)

# Combine all dataframes into one
combined_df = pd.concat(dfs.values(), ignore_index=True)

# Print the combined dataframe
print(combined_df)

In [568]:
df_cycling_1= pd.read_excel('cycling_1.xls', sheet_name=None)

In [569]:
df_cycling_1

{'Accelerometer':        Time (s)  Acceleration x (m/s^2)  Acceleration y (m/s^2)  \
 0       0.00000               -4.937590                4.652843
 1       0.01769               -4.518547                4.640880
 2       0.21769               -3.402893                4.724628
 3       0.41769               -1.966302                5.062315
 4       0.61769                3.619144                1.720140
 ...         ...                     ...                     ...
 1538  307.41769                4.248756                7.242177
 1539  307.61769                6.273981                4.352544
 1540  307.81769                4.672285                3.932305
 1541  308.01769                4.917849                2.698207
 1542  308.21769                4.835296                3.156432

       Acceleration z (m/s^2)
 0                   8.306684
 1                   8.117651
 2                   7.923533
 3                   9.719048
 4                   9.723833
 ...                      ...
 1538                9.376874
 1539                7.039086
 1540                8.697013
 1541                7.421937
 1542                7.785946

 [1543 rows x 4 columns],
 'Gyroscope':         Time (s)  Gyroscope x (rad/s)  Gyroscope y (rad/s)  \
 0       0.124068             0.058107            -0.256938
 1       0.321985            -0.334821            -1.286979
 2       0.519902            -1.759698            -1.050886
 3       0.717819            -0.644444             2.805698
 4       0.915736            -1.785888             0.112625
 ...          ...                  ...                  ...
 1477  307.392361             0.513341            -0.067499
 1478  307.600151            -0.807616            -0.343602
 1479  307.807942             0.036116            -0.026725
 1480  308.015732             0.209139            -0.016493
 1481  308.223523            -0.304736            -0.041614

       Gyroscope z (rad/s)
 0               -0.034284
 1               -0.431105
 2               -0.014889
 3                0.562590
 4                0.646200
 ...                   ...
 1477            -0.275492
 1478            -0.071469
 1479             0.086282
 1480             0.103997
 1481             0.159202

 [1482 rows x 4 columns],
 'Linear Acceleration':         Time (s)  Linear Acceleration x (m/s^2)  \
 0       0.321985                       0.000000
 1       0.519902                      -0.839092
 2       0.717819                       5.054129
 3       0.915736                       0.533491
 4       1.113653                      -3.187978
 ...          ...                            ...
 1476  307.392361                       1.008198
 1477  307.600151                      -0.944493
 1478  307.807942                       0.001666
 1479  308.015732                      -0.182450
 1480  308.223523                       0.035872

       Linear Acceleration y (m/s^2)  Linear Acceleration z (m/s^2)
 0                          0.000000                       0.000000
 1                          1.631603                      -0.337585
 2                         -0.372936                       2.048375
 3                         -0.726315                       0.175195
 4                         -3.329643                      -0.388648
 ...                             ...                            ...
 1476                      -0.860202                       0.114592
 1477                       1.895192                       0.173993
 1478                       1.436265                      -0.794128
 1479                       0.849877                      -0.236085
 1480                       1.069105                      -0.266866

 [1481 rows x 4 columns],
 'Location':        Time (s)  Latitude (°)  Longitude (°)  Height (m)  Velocity (m/s)  \
 0      3.398120     52.322133       4.981220   13.324818            1.80
 1      3.898340     52.322138       4.981194   13.021648            1.80
 2      4.915878     52.322268       4.981145    3.328813            0.65
 3      5.912670     52.322664       4.980792  -25.182358            1.61
 4      6.920771     52.322330       4.981276    7.159543            0.51
 ..          ...           ...            ...         ...             ...
 301  303.636314     52.316303       4.978808    1.566389            1.84
 302  304.646596     52.316296       4.978786    1.262290            0.87
 303  305.652215     52.316290       4.978775    1.685859            0.40
 304  306.642725     52.316279       4.978773    2.094900            0.00
 305  307.651352     52.316277       4.978775    2.362050            0.00

      Direction (°)  Horizontal Accuracy (m)  Vertical Accuracy (m)
 0       286.299988                32.846626               4.984176
 1       286.299988                35.511860               4.984176
 2       286.299988                12.971429              14.279662
 3       198.500000                36.734108              40.143154
 4       163.300003                 5.290380               6.550884
 ..             ...                      ...                    ...
 301     234.800003                 4.896246               4.435001
 302     240.399994                 4.775402               4.256435
 303     240.100006                 4.528944               3.955069
 304       0.000000                 4.534974               4.513819
 305       0.000000                 4.401075               4.349354

 [306 rows x 8 columns],
 'Magnetometer':         Time (s)  Magnetic field x (µT)  Magnetic field y (µT)  \
 0       0.168253                3.82500             -27.656252
 1       0.368253                1.83750             -27.487501
 2       0.568253               -1.48125             -24.712502
 3       0.768253                0.60000             -20.831251
 4       0.968253                3.61875             -16.668751
 ...          ...                    ...                    ...
 1536  307.465137               -3.71250             -21.525002
 1537  307.665137               -3.63750             -23.437500
 1538  307.865137               -3.86250             -24.581251
 1539  308.065137               -4.18125             -25.537500
 1540  308.265137               -4.80000             -26.362501

       Magnetic field z (µT)
 0                -34.312500
 1                -35.193752
 2                -37.406250
 3                -39.375000
 4                -40.537502
 ...                     ...
 1536             -45.468750
 1537             -44.681252
 1538             -44.025002
 1539             -43.462502
 1540             -42.956253

 [1541 rows x 4 columns],
 'Pressure':         Time (s)  Pressure (hPa)
 0       0.291757     1010.716248
 1       0.491774     1010.811218
 2       0.691786     1010.983704
 3       0.891787     1010.488708
 4       1.091778     1011.065002
 ...          ...             ...
 1536  307.491758     1010.697449
 1537  307.691760     1010.537476
 1538  307.891752     1010.731201
 1539  308.091759     1010.719971
 1540  308.291757     1010.684998

 [1541 rows x 2 columns],
 'Proximity':      Time (s)  Distance (cm)
 0    0.179544              5
 1  298.176366              0
 2  298.432800              5,
 'Metadata Device':                 proeprty      value
 0                version     1.1.11
 1                  build    1011102
 2             fileFormat       1.15
 3            deviceModel  M2102J2SC
 4            deviceBrand     Xiaomi
 ..                   ...        ...
 99   attitude Resolution       0.01
 100    attitude MinDelay       5000
 101    attitude MaxDelay     200000
 102       attitude Power      1.415
 103     attitude Version          1

 [104 rows x 2 columns],
 'Metadata Time':    event  experiment time   system time                   system time text
 0  START         0.000000  1.686683e+09  2023-06-13 20:57:04.902 UTC+02:00
 1  PAUSE       308.425261  1.686683e+09  2023-06-13 21:02:13.327 UTC+02:00}

In [570]:
#show all columns of dfs
pd.set_option('display.max_columns', None)

#combine all dataframes into on
combined_df_cycling_1 = pd.concat(df_cycling_1.values(), ignore_index=True)

In [571]:
combined_df_cycling_1

,Time (s),Acceleration x (m/s^2),Acceleration y (m/s^2),Acceleration z (m/s^2),Gyroscope x (rad/s),Gyroscope y (rad/s),Gyroscope z (rad/s),Linear Acceleration x (m/s^2),Linear Acceleration y (m/s^2),Linear Acceleration z (m/s^2),Latitude (°),Longitude (°),Height (m),Velocity (m/s),Direction (°),Horizontal Accuracy (m),Vertical Accuracy (m),Magnetic field x (µT),Magnetic field y (µT),Magnetic field z (µT),Pressure (hPa),Distance (cm),proeprty,value,event,experiment time,system time,system time text
0,0.00000,-4.937590,4.652843,8.306684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.01769,-4.518547,4.640880,8.117651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.21769,-3.402893,4.724628,7.923533,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.41769,-1.966302,5.062315,9.719048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.61769,3.619144,1.720140,9.723833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attitude MaxDelay,200000,NaN,NaN,NaN,NaN
7999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attitude Power,1.415,NaN,NaN,NaN,NaN
8000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attitude Version,1,NaN,NaN,NaN,NaN
8001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,START,0.000000,1.686683e+09,2023-06-13 20:57:04.902 UTC+02:00
8002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAUSE,308.425261,1.686683e+09,2023-06-13 21:02:13.327 UTC+02:00

In [572]:
combined_df_cycling_1 = combined_df_cycling_1.interpolate(method='linear')

In [573]:
#show missing values in each column
combined_df_cycling_1.isnull().sum()

Time (s)                            0
Acceleration x (m/s^2)              0
Acceleration y (m/s^2)              0
Acceleration z (m/s^2)              0
Gyroscope x (rad/s)              1543
Gyroscope y (rad/s)              1543
Gyroscope z (rad/s)              1543
Linear Acceleration x (m/s^2)    3025
Linear Acceleration y (m/s^2)    3025
Linear Acceleration z (m/s^2)    3025
Latitude (°)                     4506
Longitude (°)                    4506
Height (m)                       4506
Velocity (m/s)                   4506
Direction (°)                    4506
Horizontal Accuracy (m)          4506
Vertical Accuracy (m)            4506
Magnetic field x (µT)            4812
Magnetic field y (µT)            4812
Magnetic field z (µT)            4812
Pressure (hPa)                   6353
Distance (cm)                    7894
proeprty                         7899
value                            7920
event                            8001
experiment time                  8001
system time                      8001
system time text                 8001
dtype: int64

In [574]:
combined_df_cycling_1= combined_df_cycling_1.ffill().bfill()

In [575]:
#drop last seven columns
combined_df_cycling_1 = combined_df_cycling_1.iloc[:, :-7]

In [576]:
combined_df_cycling_1

,Time (s),Acceleration x (m/s^2),Acceleration y (m/s^2),Acceleration z (m/s^2),Gyroscope x (rad/s),Gyroscope y (rad/s),Gyroscope z (rad/s),Linear Acceleration x (m/s^2),Linear Acceleration y (m/s^2),Linear Acceleration z (m/s^2),Latitude (°),Longitude (°),Height (m),Velocity (m/s),Direction (°),Horizontal Accuracy (m),Vertical Accuracy (m),Magnetic field x (µT),Magnetic field y (µT),Magnetic field z (µT),Pressure (hPa)
0,0.00000,-4.937590,4.652843,8.306684,0.058107,-0.256938,-0.034284,0.000000,0.000000,0.000000,52.322133,4.981220,13.324818,1.8,286.299988,32.846626,4.984176,3.825,-27.656252,-34.312500,1010.716248
1,0.01769,-4.518547,4.640880,8.117651,0.058107,-0.256938,-0.034284,0.000000,0.000000,0.000000,52.322133,4.981220,13.324818,1.8,286.299988,32.846626,4.984176,3.825,-27.656252,-34.312500,1010.716248
2,0.21769,-3.402893,4.724628,7.923533,0.058107,-0.256938,-0.034284,0.000000,0.000000,0.000000,52.322133,4.981220,13.324818,1.8,286.299988,32.846626,4.984176,3.825,-27.656252,-34.312500,1010.716248
3,0.41769,-1.966302,5.062315,9.719048,0.058107,-0.256938,-0.034284,0.000000,0.000000,0.000000,52.322133,4.981220,13.324818,1.8,286.299988,32.846626,4.984176,3.825,-27.656252,-34.312500,1010.716248
4,0.61769,3.619144,1.720140,9.723833,0.058107,-0.256938,-0.034284,0.000000,0.000000,0.000000,52.322133,4.981220,13.324818,1.8,286.299988,32.846626,4.984176,3.825,-27.656252,-34.312500,1010.716248
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7998,298.43280,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,0.035872,1.069105,-0.266866,52.316277,4.978775,2.362050,0.0,0.000000,4.401075,4.349354,-4.800,-26.362501,-42.956253,1010.684998
7999,298.43280,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,0.035872,1.069105,-0.266866,52.316277,4.978775,2.362050,0.0,0.000000,4.401075,4.349354,-4.800,-26.362501,-42.956253,1010.684998
8000,298.43280,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,0.035872,1.069105,-0.266866,52.316277,4.978775,2.362050,0.0,0.000000,4.401075,4.349354,-4.800,-26.362501,-42.956253,1010.684998
8001,298.43280,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,0.035872,1.069105,-0.266866,52.316277,4.978775,2.362050,0.0,0.000000,4.401075,4.349354,-4.800,-26.362501,-42.956253,1010.684998
8002,298.43280,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,0.035872,1.069105,-0.266866,52.316277,4.978775,2.362050,0.0,0.000000,4.401075,4.349354,-4.800,-26.362501,-42.956253,1010.684998

In [577]:
#drop Linear Acceleration x (m/s^2)	Linear Acceleration y (m/s^2)	Linear Acceleration z (m/s^2)	Latitude (°)	Longitude (°)	Height (m)	Velocity (m/s)	Direction (°)	Horizontal Accuracy (m)	Vertical Accuracy (m)	Magnetic field x (µT)	Magnetic field y (µT)	Magnetic field z (µT)	Pressure (hPa)	Distance (cm)	proeprty	value	event	experiment time	system time	system time text
combined_df_cycling_1 = combined_df_cycling_1.drop(['Linear Acceleration x (m/s^2)', 'Linear Acceleration y (m/s^2)', 'Linear Acceleration z (m/s^2)', 'Latitude (°)', 'Longitude (°)', 'Height (m)', 'Velocity (m/s)', 'Direction (°)', 'Horizontal Accuracy (m)', 'Vertical Accuracy (m)', 'Magnetic field x (µT)', 'Magnetic field y (µT)', 'Magnetic field z (µT)', 'Pressure (hPa)'], axis=1)

In [578]:
df_doppler_cycling_1= pd.read_excel('doppler_cycling_1.xls', sheet_name=None)
#show all columns of dfs
pd.set_option('display.max_columns', None)

#combine all dataframes into on
combined_df_doppler_cycling_1 = pd.concat(df_doppler_cycling_1.values(), ignore_index=True)
combined_df_doppler_cycling_1

,Time (s),Frequency (Hz),Speed (m/s),property,value,event,experiment time,system time,system time text
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.847479,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.897480,1003.170769,1.074654,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
6358,NaN,NaN,NaN,depthBackSensor,0,NaN,NaN,NaN,NaN
6359,NaN,NaN,NaN,depthBackResolution,NaN,NaN,NaN,NaN,NaN
6360,NaN,NaN,NaN,depthBackRate,NaN,NaN,NaN,NaN,NaN
6361,NaN,NaN,NaN,NaN,NaN,START,0.000000,1.686683e+09,2023-06-13 20:57:01.081 UTC+02:00
6362,NaN,NaN,NaN,NaN,NaN,PAUSE,317.733696,1.686683e+09,2023-06-13 21:02:18.815 UTC+02:00

In [579]:
#remove columns property, value, event, experiment time, system time and sytem time text from combined_df_doppler_cycling_1
combined_df_doppler_cycling_1 = combined_df_doppler_cycling_1.drop(['property', 'value', 'event', 'experiment time', 'system time', 'system time text'], axis=1)
combined_df_doppler_cycling_1

      Time (s)  Frequency (Hz)  Speed (m/s)
0          NaN             NaN          NaN
1          NaN             NaN          NaN
2          NaN             NaN          NaN
3     0.847479             NaN          NaN
4     0.897480     1003.170769     1.074654
...        ...             ...          ...
6358       NaN             NaN          NaN
6359       NaN             NaN          NaN
6360       NaN             NaN          NaN
6361       NaN             NaN          NaN
6362       NaN             NaN          NaN

[6363 rows x 3 columns]

In [585]:
combined_df_doppler_cycling_1 = combined_df_doppler_cycling_1.interpolate(method='linear')

In [586]:
combined_df_doppler_cycling_1.isna().sum()

Frequency (Hz)    4
Speed (m/s)       4
dtype: int64

In [587]:
combined_df_doppler_cycling_1

      Frequency (Hz)  Speed (m/s)
0                NaN          NaN
1                NaN          NaN
2                NaN          NaN
3                NaN          NaN
4        1003.170769     1.074654
...              ...          ...
6358     1001.481353     0.502915
6359     1001.481353     0.502915
6360     1001.481353     0.502915
6361     1001.481353     0.502915
6362     1001.481353     0.502915

[6363 rows x 2 columns]

In [583]:
#drop first colum 
combined_df_doppler_cycling_1 = combined_df_doppler_cycling_1.iloc[:, 1:]

In [588]:
#drop first four rows
combined_df_doppler_cycling_1 = combined_df_doppler_cycling_1.iloc[4:, :]

In [792]:
combined_df_doppler_cycling_1

      Frequency (Hz)  Speed (m/s)
4        1003.170769     1.074654
5        1001.437081     0.485868
6         999.703393    -0.102918
7         997.969706    -0.691704
8         996.866920    -1.068595
...              ...          ...
6358     1001.481353     0.502915
6359     1001.481353     0.502915
6360     1001.481353     0.502915
6361     1001.481353     0.502915
6362     1001.481353     0.502915

[6359 rows x 2 columns]

In [795]:
#combine combined_df_doppler_cycling_1 and combined_df_cycling_1
combined_df_cycling_1 = pd.concat([combined_df_cycling_1, combined_df_doppler_cycling_1], axis=1)

In [591]:
combined_df_cycling_1.isna().sum()

Time (s)                     0
Acceleration x (m/s^2)       0
Acceleration y (m/s^2)       0
Acceleration z (m/s^2)       0
Gyroscope x (rad/s)          0
Gyroscope y (rad/s)          0
Gyroscope z (rad/s)          0
Frequency (Hz)            1644
Speed (m/s)               1644
dtype: int64

In [593]:
combined_df_cycling_1 = combined_df_cycling_1.interpolate(method='linear')

In [796]:
combined_df_cycling_1

,Time (s),Acceleration x (m/s^2),Acceleration y (m/s^2),Acceleration z (m/s^2),Gyroscope x (rad/s),Gyroscope y (rad/s),Gyroscope z (rad/s),Frequency (Hz),Speed (m/s),Frequency (Hz),Speed (m/s),Frequency (Hz),Speed (m/s)
0,0.00000,-4.937590,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654,NaN,NaN,NaN,NaN
1,0.01769,-4.518547,4.640880,8.117651,0.058107,-0.256938,-0.034284,1003.170769,1.074654,NaN,NaN,NaN,NaN
2,0.21769,-3.402893,4.724628,7.923533,0.058107,-0.256938,-0.034284,1003.170769,1.074654,NaN,NaN,NaN,NaN
3,0.41769,-1.966302,5.062315,9.719048,0.058107,-0.256938,-0.034284,1003.170769,1.074654,NaN,NaN,NaN,NaN
4,0.61769,3.619144,1.720140,9.723833,0.058107,-0.256938,-0.034284,1003.170769,1.074654,1003.170769,1.074654,1003.170769,1.074654
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7998,298.43280,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1001.481353,0.502915,NaN,NaN,NaN,NaN
7999,298.43280,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1001.481353,0.502915,NaN,NaN,NaN,NaN
8000,298.43280,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1001.481353,0.502915,NaN,NaN,NaN,NaN
8001,298.43280,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1001.481353,0.502915,NaN,NaN,NaN,NaN
8002,298.43280,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1001.481353,0.502915,NaN,NaN,NaN,NaN

In [594]:
combined_df_cycling_1= combined_df_cycling_1.ffill().bfill()

In [595]:
combined_df_cycling_1

,Time (s),Acceleration x (m/s^2),Acceleration y (m/s^2),Acceleration z (m/s^2),Gyroscope x (rad/s),Gyroscope y (rad/s),Gyroscope z (rad/s),Frequency (Hz),Speed (m/s)
0,0.00000,-4.937590,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
1,0.01769,-4.518547,4.640880,8.117651,0.058107,-0.256938,-0.034284,1003.170769,1.074654
2,0.21769,-3.402893,4.724628,7.923533,0.058107,-0.256938,-0.034284,1003.170769,1.074654
3,0.41769,-1.966302,5.062315,9.719048,0.058107,-0.256938,-0.034284,1003.170769,1.074654
4,0.61769,3.619144,1.720140,9.723833,0.058107,-0.256938,-0.034284,1003.170769,1.074654
...,...,...,...,...,...,...,...,...,...
7998,298.43280,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1001.481353,0.502915
7999,298.43280,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1001.481353,0.502915
8000,298.43280,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1001.481353,0.502915
8001,298.43280,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1001.481353,0.502915
8002,298.43280,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1001.481353,0.502915

In [596]:
selected_sheet = ['Accelerometer', 'Gyroscope']

In [597]:
df_cycling_2= pd.read_excel('cycling_1.xls', sheet_name=selected_sheet)

In [598]:
df_cycling_2

{'Accelerometer':        Time (s)  Acceleration x (m/s^2)  Acceleration y (m/s^2)  \
 0       0.00000               -4.937590                4.652843
 1       0.01769               -4.518547                4.640880
 2       0.21769               -3.402893                4.724628
 3       0.41769               -1.966302                5.062315
 4       0.61769                3.619144                1.720140
 ...         ...                     ...                     ...
 1538  307.41769                4.248756                7.242177
 1539  307.61769                6.273981                4.352544
 1540  307.81769                4.672285                3.932305
 1541  308.01769                4.917849                2.698207
 1542  308.21769                4.835296                3.156432

       Acceleration z (m/s^2)
 0                   8.306684
 1                   8.117651
 2                   7.923533
 3                   9.719048
 4                   9.723833
 ...                      ...
 1538                9.376874
 1539                7.039086
 1540                8.697013
 1541                7.421937
 1542                7.785946

 [1543 rows x 4 columns],
 'Gyroscope':         Time (s)  Gyroscope x (rad/s)  Gyroscope y (rad/s)  \
 0       0.124068             0.058107            -0.256938
 1       0.321985            -0.334821            -1.286979
 2       0.519902            -1.759698            -1.050886
 3       0.717819            -0.644444             2.805698
 4       0.915736            -1.785888             0.112625
 ...          ...                  ...                  ...
 1477  307.392361             0.513341            -0.067499
 1478  307.600151            -0.807616            -0.343602
 1479  307.807942             0.036116            -0.026725
 1480  308.015732             0.209139            -0.016493
 1481  308.223523            -0.304736            -0.041614

       Gyroscope z (rad/s)
 0               -0.034284
 1               -0.431105
 2               -0.014889
 3                0.562590
 4                0.646200
 ...                   ...
 1477            -0.275492
 1478            -0.071469
 1479             0.086282
 1480             0.103997
 1481             0.159202

 [1482 rows x 4 columns]}

In [599]:
#show all columns of dfs
pd.set_option('display.max_columns', None)

#combine all dataframes into on
combined_df_cycling_2 = pd.concat(df_cycling_2.values(), ignore_index=True)

In [600]:
combined_df_cycling_2 = combined_df_cycling_2.interpolate(method='linear')

In [601]:
combined_df_cycling_2 = combined_df_cycling_2.ffill().bfill()

In [602]:
combined_df_cycling_2

,Time (s),Acceleration x (m/s^2),Acceleration y (m/s^2),Acceleration z (m/s^2),Gyroscope x (rad/s),Gyroscope y (rad/s),Gyroscope z (rad/s)
0,0.000000,-4.937590,4.652843,8.306684,0.058107,-0.256938,-0.034284
1,0.017690,-4.518547,4.640880,8.117651,0.058107,-0.256938,-0.034284
2,0.217690,-3.402893,4.724628,7.923533,0.058107,-0.256938,-0.034284
3,0.417690,-1.966302,5.062315,9.719048,0.058107,-0.256938,-0.034284
4,0.617690,3.619144,1.720140,9.723833,0.058107,-0.256938,-0.034284
...,...,...,...,...,...,...,...
3020,307.392361,4.835296,3.156432,7.785946,0.513341,-0.067499,-0.275492
3021,307.600151,4.835296,3.156432,7.785946,-0.807616,-0.343602,-0.071469
3022,307.807942,4.835296,3.156432,7.785946,0.036116,-0.026725,0.086282
3023,308.015732,4.835296,3.156432,7.785946,0.209139,-0.016493,0.103997
3024,308.223523,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202

In [603]:
df_doppler_cycling_2= pd.read_excel('doppler_cycling_2.xls', sheet_name=None)
#show all columns of dfs
pd.set_option('display.max_columns', None)

#combine all dataframes into on
combined_df_doppler_cycling_2 = pd.concat(df_doppler_cycling_2.values(), ignore_index=True)
combined_df_doppler_cycling_2

,Time (s),Frequency (Hz),Speed (m/s),property,value,event,experiment time,system time,system time text
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.849678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.899679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.949680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
7990,NaN,NaN,NaN,depthFrontRate,NaN,NaN,NaN,NaN,NaN
7991,NaN,NaN,NaN,depthBackSensor,0,NaN,NaN,NaN,NaN
7992,NaN,NaN,NaN,depthBackResolution,NaN,NaN,NaN,NaN,NaN
7993,NaN,NaN,NaN,depthBackRate,NaN,NaN,NaN,NaN,NaN
7994,NaN,NaN,NaN,NaN,NaN,START,0.0,1.686684e+09,2023-06-13 21:25:33.333 UTC+02:00

In [604]:
#remove columns property, value, event, experiment time, system time and sytem time text from combined_df_doppler_cycling_1
combined_df_doppler_cycling_2 = combined_df_doppler_cycling_2.drop(['property', 'value', 'event', 'experiment time', 'system time', 'system time text'], axis=1)
combined_df_doppler_cycling_2

      Time (s)  Frequency (Hz)  Speed (m/s)
0          NaN             NaN          NaN
1          NaN             NaN          NaN
2     0.849678             NaN          NaN
3     0.899679             NaN          NaN
4     0.949680             NaN          NaN
...        ...             ...          ...
7990       NaN             NaN          NaN
7991       NaN             NaN          NaN
7992       NaN             NaN          NaN
7993       NaN             NaN          NaN
7994       NaN             NaN          NaN

[7995 rows x 3 columns]

In [605]:
combined_df_doppler_cycling_2 = combined_df_doppler_cycling_2.interpolate(method='linear')

In [606]:
combined_df_doppler_cycling_2 = combined_df_doppler_cycling_2.ffill().bfill()

In [609]:
combined_df_doppler_cycling_2

      Frequency (Hz)  Speed (m/s)
0        1000.775093     0.263327
1        1000.775093     0.263327
2        1000.775093     0.263327
3        1000.775093     0.263327
4        1000.775093     0.263327
...              ...          ...
7990     1004.414087     1.494194
7991     1004.414087     1.494194
7992     1004.414087     1.494194
7993     1004.414087     1.494194
7994     1004.414087     1.494194

[7995 rows x 2 columns]

In [608]:
#drop first colum
combined_df_doppler_cycling_2 = combined_df_doppler_cycling_2.iloc[:, 1:]

In [610]:
#merge combined_df_cycling_2 and combined_df_doppler_cycling_2
combined_df_cycling_2 = pd.concat([combined_df_cycling_2, combined_df_doppler_cycling_2], axis=1)

In [611]:
combined_df_cycling_2 = combined_df_cycling_2.interpolate(method='linear')
combined_df_cycling_2 = combined_df_cycling_2.ffill().bfill()

In [612]:
combined_df_cycling_2

,Time (s),Acceleration x (m/s^2),Acceleration y (m/s^2),Acceleration z (m/s^2),Gyroscope x (rad/s),Gyroscope y (rad/s),Gyroscope z (rad/s),Frequency (Hz),Speed (m/s)
0,0.000000,-4.937590,4.652843,8.306684,0.058107,-0.256938,-0.034284,1000.775093,0.263327
1,0.017690,-4.518547,4.640880,8.117651,0.058107,-0.256938,-0.034284,1000.775093,0.263327
2,0.217690,-3.402893,4.724628,7.923533,0.058107,-0.256938,-0.034284,1000.775093,0.263327
3,0.417690,-1.966302,5.062315,9.719048,0.058107,-0.256938,-0.034284,1000.775093,0.263327
4,0.617690,3.619144,1.720140,9.723833,0.058107,-0.256938,-0.034284,1000.775093,0.263327
...,...,...,...,...,...,...,...,...,...
7990,308.223523,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7991,308.223523,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7992,308.223523,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7993,308.223523,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7994,308.223523,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194

In [613]:
#merge combined_df_cycling_1 and combined_df_cycling_2
combined_df_cycling = pd.concat([combined_df_cycling_1, combined_df_cycling_2], axis=0)

In [657]:
combined_df_cycling

,Time (s),cycling_A_x,cycling_A_y,cycling_A_z,cycling_Gyr_x,cycling_Gyr_y,cycling_Gyr_z,cycling_freq,cycling_speed
0,0.000000,-4.937590,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
1,0.017690,-4.518547,4.640880,8.117651,0.058107,-0.256938,-0.034284,1003.170769,1.074654
2,0.217690,-3.402893,4.724628,7.923533,0.058107,-0.256938,-0.034284,1003.170769,1.074654
3,0.417690,-1.966302,5.062315,9.719048,0.058107,-0.256938,-0.034284,1003.170769,1.074654
4,0.617690,3.619144,1.720140,9.723833,0.058107,-0.256938,-0.034284,1003.170769,1.074654
...,...,...,...,...,...,...,...,...,...
7990,308.223523,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7991,308.223523,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7992,308.223523,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7993,308.223523,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7994,308.223523,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194

In [652]:
#rename columns of combined_df_cycling
combined_df_cycling = combined_df_cycling.rename(columns={'Acceleration x (m/s^2)': 'cycling_A_x', 'Acceleration y (m/s^2)': 'cycling_A_y', 'Acceleration z (m/s^2)': 'cycling_A_z', 'Gyroscope x (rad/s)': 'cycling_Gyr_x', 'Gyroscope y (rad/s)': 'cycling_Gyr_y', 'Gyroscope z (rad/s)': 'cycling_Gyr_z', 'Doppler Speed (m/s)': 'cycling_doppler_speed', 'Doppler Distance (m)': 'cycing_doppler_distance'})

In [654]:
combined_df_cycling = combined_df_cycling.rename(columns={'Acceleration x (m/s^2)': 'cycling_A_x', 'Acceleration y (m/s^2)': 'cycling_A_y', 'Acceleration z (m/s^2)': 'cycling_A_z'})

In [656]:
combined_df_cycling = combined_df_cycling.rename(columns={'Frequency (Hz)':'cycling_freq', 'Speed (m/s)': 'cycling_speed'})

Walking

In [615]:
selected_sheet_walking = ['Linear Accelerometer', 'Gyroscope']
df_walking_1= pd.read_excel('walking_1.xls', sheet_name=selected_sheet_walking)

In [616]:
#show all columns of dfs
pd.set_option('display.max_columns', None)

#combine all dataframes into on
df_walking_1 = pd.concat(df_walking_1.values(), ignore_index=True)

In [617]:
df_walking_1 = df_walking_1.interpolate(method='linear')
df_walking_1 = df_walking_1.ffill().bfill()

In [618]:
df_walking_1

,Time (s),X (m/s^2),Y (m/s^2),Z (m/s^2),X (rad/s),Y (rad/s),Z (rad/s)
0,0.200265,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363
1,0.400889,-0.131220,-0.012420,-0.090599,-0.049143,-0.088391,0.005363
2,0.601513,0.024113,0.104459,0.156629,-0.049143,-0.088391,0.005363
3,0.802138,0.957141,-0.472767,0.644791,-0.049143,-0.088391,0.005363
4,1.002762,0.330834,-0.696418,-0.121794,-0.049143,-0.088391,0.005363
...,...,...,...,...,...,...,...
18347,1840.165761,-0.157216,-0.482441,-0.489857,-0.087972,0.041102,-0.125695
18348,1840.366386,-0.157216,-0.482441,-0.489857,-0.057422,0.423214,0.321369
18349,1840.567012,-0.157216,-0.482441,-0.489857,-0.210623,0.565993,0.481988
18350,1840.767637,-0.157216,-0.482441,-0.489857,0.021674,0.723518,0.730931
18351,1840.968262,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739

In [619]:
df_walking_1_doppler = pd.read_csv('D_Frequency_speed_1.csv')

In [620]:
df_walking_1_doppler = df_walking_1_doppler.interpolate(method='linear')
df_walking_1_doppler = df_walking_1_doppler.ffill().bfill()

In [622]:
df_walking_1_doppler.isnull().sum()

Time (s)          0
Frequency (Hz)    0
Speed (m/s)       0
dtype: int64

In [623]:
#drop first colum
df_walking_1_doppler = df_walking_1_doppler.iloc[:, 1:]

In [624]:
#merge df_walking_1 and df_walking_1_doppler
df_walking_1 = pd.concat([df_walking_1, df_walking_1_doppler], axis=1)

In [625]:
df_walking_1 = df_walking_1.interpolate(method='linear')
df_walking_1 = df_walking_1.ffill().bfill()

In [627]:
df_walking_1.isnull().sum()

Time (s)          0
X (m/s^2)         0
Y (m/s^2)         0
Z (m/s^2)         0
X (rad/s)         0
Y (rad/s)         0
Z (rad/s)         0
Frequency (Hz)    0
Speed (m/s)       0
dtype: int64

In [628]:
selected_sheet_walking = ['Accelerometer', 'Gyroscope']
df_walking_2= pd.read_excel('walking_2.xls', sheet_name=selected_sheet_walking)

In [629]:
#show all columns of dfs
pd.set_option('display.max_columns', None)

#combine all dataframes into on
df_walking_2 = pd.concat(df_walking_2.values(), ignore_index=True)
df_walking_2 = df_walking_2.interpolate(method='linear')
df_walking_2 = df_walking_2.ffill().bfill()

In [630]:
df_walking_2_doppler = pd.read_excel('doppler_walking_2.xls')

In [631]:
df_walking_2_doppler

        Time (s)  Frequency (Hz)  Speed (m/s)
0       0.231000             NaN          NaN
1       0.281001             NaN          NaN
2       0.833000             NaN          NaN
3       0.883001             NaN          NaN
4       0.933002             NaN          NaN
...          ...             ...          ...
8638  432.646008             NaN          NaN
8639  432.696009             NaN          NaN
8640  432.746010             NaN          NaN
8641  432.796012             NaN     -0.85698
8642    0.000000             NaN          NaN

[8643 rows x 3 columns]

In [632]:
df_walking_2_doppler = df_walking_2_doppler.interpolate(method='linear')
df_walking_2_doppler = df_walking_2_doppler.ffill().bfill()

In [633]:
#drop first colum
df_walking_2_doppler = df_walking_2_doppler.iloc[:, 1:]

In [634]:
#merge df_walking_2 and df_walking_2_doppler and interpolate
df_walking_2 = pd.concat([df_walking_2, df_walking_2_doppler], axis=1)

In [635]:
df_walking_2 = df_walking_2.interpolate(method='linear')
df_walking_2 = df_walking_2.ffill().bfill()

In [636]:
df_walking_2

,Time (s),Acceleration x (m/s^2),Acceleration y (m/s^2),Acceleration z (m/s^2),Gyroscope x (rad/s),Gyroscope y (rad/s),Gyroscope z (rad/s),Frequency (Hz),Speed (m/s)
0,0.101264,-4.170690,6.213861,7.041778,-0.148054,-0.902680,-0.219676,1000.597433,0.203006
1,0.309099,-1.837090,5.478068,8.142476,-0.148054,-0.902680,-0.219676,1000.597433,0.203006
2,0.516934,-2.846562,4.747958,8.282756,-0.148054,-0.902680,-0.219676,1000.597433,0.203006
3,0.724769,-1.897807,7.566703,6.110372,-0.148054,-0.902680,-0.219676,1000.597433,0.203006
4,0.932604,0.948156,8.023434,-3.462713,-0.148054,-0.902680,-0.219676,1000.597433,0.203006
...,...,...,...,...,...,...,...,...,...
8638,433.402671,-0.488734,4.994718,8.481659,-0.002138,0.002902,0.002520,997.485809,-0.076273
8639,433.402671,-0.488734,4.994718,8.481659,-0.002138,0.002902,0.002520,997.485809,-0.336509
8640,433.402671,-0.488734,4.994718,8.481659,-0.002138,0.002902,0.002520,997.485809,-0.596744
8641,433.402671,-0.488734,4.994718,8.481659,-0.002138,0.002902,0.002520,997.485809,-0.856980
8642,433.402671,-0.488734,4.994718,8.481659,-0.002138,0.002902,0.002520,997.485809,-0.856980

In [637]:
#change column names to Time (s)	X (m/s^2)	Y (m/s^2)	Z (m/s^2)	X (rad/s)	Y (rad/s)	Z (rad/s)	Time (s)	Frequency (Hz)	Speed (m/s)
df_walking_2.columns = ['Time (s)', 'X (m/s^2)', 'Y (m/s^2)', 'Z (m/s^2)', 'X (rad/s)', 'Y (rad/s)', 'Z (rad/s)', 'Frequency (Hz)', 'Speed (m/s)']

In [638]:
#merge df_walking_1 and df_walking_2 with pd.concat
df_walking = pd.concat([df_walking_1, df_walking_2], axis=0)

In [640]:
df_walking.isnull().sum()

Time (s)          0
X (m/s^2)         0
Y (m/s^2)         0
Z (m/s^2)         0
X (rad/s)         0
Y (rad/s)         0
Z (rad/s)         0
Frequency (Hz)    0
Speed (m/s)       0
dtype: int64

In [659]:
df_walking

,Time (s),walking_A_x,walking_A_y,walking_A_z,walking_Gyr_x,walking_Gyr_y,walking_Gyr_z,walking_freq,walking_speed
0,0.200265,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204
1,0.400889,-0.131220,-0.012420,-0.090599,-0.049143,-0.088391,0.005363,1001.351905,0.459017
2,0.601513,0.024113,0.104459,0.156629,-0.049143,-0.088391,0.005363,1001.395617,0.473829
3,0.802138,0.957141,-0.472767,0.644791,-0.049143,-0.088391,0.005363,1001.439330,0.488642
4,1.002762,0.330834,-0.696418,-0.121794,-0.049143,-0.088391,0.005363,1001.483042,0.503454
...,...,...,...,...,...,...,...,...,...
8638,433.402671,-0.488734,4.994718,8.481659,-0.002138,0.002902,0.002520,997.485809,-0.076273
8639,433.402671,-0.488734,4.994718,8.481659,-0.002138,0.002902,0.002520,997.485809,-0.336509
8640,433.402671,-0.488734,4.994718,8.481659,-0.002138,0.002902,0.002520,997.485809,-0.596744
8641,433.402671,-0.488734,4.994718,8.481659,-0.002138,0.002902,0.002520,997.485809,-0.856980
8642,433.402671,-0.488734,4.994718,8.481659,-0.002138,0.002902,0.002520,997.485809,-0.856980

In [658]:
#rename columns 
df_walking = df_walking.rename(columns={'X (m/s^2)':'walking_A_x', 'Y (m/s^2)':'walking_A_y', 'Z (m/s^2)':'walking_A_z', 'X (rad/s)':'walking_Gyr_x', 'Y (rad/s)':'walking_Gyr_y', 'Z (rad/s)':'walking_Gyr_z', 'Frequency (Hz)':'walking_freq', 'Speed (m/s)': 'walking_speed'})

Metro

In [777]:
selected_sheet_walking = ['Accelerometer', 'Gyroscope']
df_metro= pd.read_excel('metro_1.xls', sheet_name=selected_sheet_walking)

In [783]:
#show column gyroscope x
len(df_metro['Gyroscope x (rad/s)'].unique())

1439

In [779]:
#show all columns of dfs
pd.set_option('display.max_columns', None)

#combine all dataframes into on
df_metro = pd.concat(df_metro.values(), ignore_index=True)
#df_metro = df_metro.interpolate(method='linear')
#df_metro = df_metro.ffill().bfill()

In [643]:
df_metro_doppler = pd.read_excel('doppler_metro_1.xls')

In [786]:
df_metro_doppler

      Frequency (Hz)  Speed (m/s)
0        1000.597433     0.203006
1        1000.597433     0.203006
2        1000.597433     0.203006
3        1000.597433     0.203006
4        1000.597433     0.203006
...              ...          ...
8638      997.485809    -0.076273
8639      997.485809    -0.336509
8640      997.485809    -0.596744
8641      997.485809    -0.856980
8642      997.485809    -0.856980

[8643 rows x 2 columns]

In [789]:
df_metro_doppler.isna().sum()

Frequency (Hz)    0
Speed (m/s)       0
dtype: int64

In [645]:
df_metro_doppler = df_metro_doppler.interpolate(method='linear')
df_metro_doppler = df_metro_doppler.ffill().bfill()

In [646]:
#drop first colum
df_metro_doppler = df_metro_doppler.iloc[:, 1:]

In [647]:
#combine df_metro and df_metro_doppler
df_metro = pd.concat([df_metro, df_metro_doppler], axis=1)

In [663]:
df_metro

,Time (s),metro_A_x,metro_A_y,metro_A_z,metro_Gyr_x,metro_Gyr_y,metro_Gyr_z,metro_doppler_frequ,metro_doppler_speed
0,0.105310,-4.346861,8.560024,1.084248,-0.353604,-0.120108,0.050013,1000.597433,0.203006
1,0.313140,-3.879065,8.463713,1.387837,-0.353604,-0.120108,0.050013,1000.597433,0.203006
2,0.520969,-2.958127,9.157033,1.877468,-0.353604,-0.120108,0.050013,1000.597433,0.203006
3,0.728799,-1.050449,9.868599,1.626222,-0.353604,-0.120108,0.050013,1000.597433,0.203006
4,0.936629,-0.005384,9.833604,1.721935,-0.353604,-0.120108,0.050013,1000.597433,0.203006
...,...,...,...,...,...,...,...,...,...
8638,651.310263,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.076273
8639,651.310263,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.336509
8640,651.310263,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.596744
8641,651.310263,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980
8642,651.310263,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980

In [649]:
df_metro = df_metro.interpolate(method='linear')
df_metro = df_metro.ffill().bfill()

In [660]:
df_metro= df_metro.rename(columns={'Acceleration x (m/s^2)': 'metro_A_x', 'Acceleration y (m/s^2)': 'metro_A_y', 'Acceleration z (m/s^2)': 'metro_A_z', 'Gyroscope x (rad/s)': 'metro_Gyr_x', 'Gyroscope y (rad/s)': 'metro_Gyr_y', 'Gyroscope z (rad/s)': 'metro_Gyr_z', 'Frequency (Hz)': 'metro_doppler_frequ', 'Speed (m/s)': 'metro_doppler_speed'})

In [662]:
df_metro = df_metro.rename(columns={'Frequency (Hz)': 'metro_doppler_frequ'})

In [651]:
df_metro.isnull().sum()

Time (s)                  0
Acceleration x (m/s^2)    0
Acceleration y (m/s^2)    0
Acceleration z (m/s^2)    0
Gyroscope x (rad/s)       0
Gyroscope y (rad/s)       0
Gyroscope z (rad/s)       0
Frequency (Hz)            0
Speed (m/s)               0
dtype: int64

In [747]:
#merge df_metro and df_walking and combined_df_cycling
df_all = pd.concat([df_metro, df_walking, combined_df_cycling], axis=0)

In [748]:
df_all

,Time (s),metro_A_x,metro_A_y,metro_A_z,metro_Gyr_x,metro_Gyr_y,metro_Gyr_z,metro_doppler_frequ,metro_doppler_speed,walking_A_x,walking_A_y,walking_A_z,walking_Gyr_x,walking_Gyr_y,walking_Gyr_z,walking_freq,walking_speed,cycling_A_x,cycling_A_y,cycling_A_z,cycling_Gyr_x,cycling_Gyr_y,cycling_Gyr_z,cycling_freq,cycling_speed
0,0.105310,-4.346861,8.560024,1.084248,-0.353604,-0.120108,0.050013,1000.597433,0.203006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.313140,-3.879065,8.463713,1.387837,-0.353604,-0.120108,0.050013,1000.597433,0.203006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.520969,-2.958127,9.157033,1.877468,-0.353604,-0.120108,0.050013,1000.597433,0.203006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.728799,-1.050449,9.868599,1.626222,-0.353604,-0.120108,0.050013,1000.597433,0.203006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.936629,-0.005384,9.833604,1.721935,-0.353604,-0.120108,0.050013,1000.597433,0.203006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7990,308.223523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7991,308.223523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7992,308.223523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7993,308.223523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7994,308.223523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194

In [749]:
df_all = df_all.interpolate(method='linear')

In [750]:
import pandas as pd
from scipy.interpolate import CubicSpline

In [751]:
df_all = df_all.ffill().bfill()

In [752]:
df_all.isnull().sum()

Time (s)               0
metro_A_x              0
metro_A_y              0
metro_A_z              0
metro_Gyr_x            0
metro_Gyr_y            0
metro_Gyr_z            0
metro_doppler_frequ    0
metro_doppler_speed    0
walking_A_x            0
walking_A_y            0
walking_A_z            0
walking_Gyr_x          0
walking_Gyr_y          0
walking_Gyr_z          0
walking_freq           0
walking_speed          0
cycling_A_x            0
cycling_A_y            0
cycling_A_z            0
cycling_Gyr_x          0
cycling_Gyr_y          0
cycling_Gyr_z          0
cycling_freq           0
cycling_speed          0
dtype: int64

In [753]:
df_all

,Time (s),metro_A_x,metro_A_y,metro_A_z,metro_Gyr_x,metro_Gyr_y,metro_Gyr_z,metro_doppler_frequ,metro_doppler_speed,walking_A_x,walking_A_y,walking_A_z,walking_Gyr_x,walking_Gyr_y,walking_Gyr_z,walking_freq,walking_speed,cycling_A_x,cycling_A_y,cycling_A_z,cycling_Gyr_x,cycling_Gyr_y,cycling_Gyr_z,cycling_freq,cycling_speed
0,0.105310,-4.346861,8.560024,1.084248,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.937590,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
1,0.313140,-3.879065,8.463713,1.387837,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.937590,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
2,0.520969,-2.958127,9.157033,1.877468,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.937590,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
3,0.728799,-1.050449,9.868599,1.626222,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.937590,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
4,0.936629,-0.005384,9.833604,1.721935,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.937590,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7990,308.223523,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.488734,4.994718,8.481659,-0.002138,0.002902,0.002520,997.485809,-0.856980,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7991,308.223523,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.488734,4.994718,8.481659,-0.002138,0.002902,0.002520,997.485809,-0.856980,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7992,308.223523,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.488734,4.994718,8.481659,-0.002138,0.002902,0.002520,997.485809,-0.856980,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7993,308.223523,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.488734,4.994718,8.481659,-0.002138,0.002902,0.002520,997.485809,-0.856980,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194
7994,308.223523,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.488734,4.994718,8.481659,-0.002138,0.002902,0.002520,997.485809,-0.856980,4.835296,3.156432,7.785946,-0.304736,-0.041614,0.159202,1004.414087,1.494194

In [754]:

df_all = df_all.iloc[:-30000, :]
df_all

,Time (s),metro_A_x,metro_A_y,metro_A_z,metro_Gyr_x,metro_Gyr_y,metro_Gyr_z,metro_doppler_frequ,metro_doppler_speed,walking_A_x,walking_A_y,walking_A_z,walking_Gyr_x,walking_Gyr_y,walking_Gyr_z,walking_freq,walking_speed,cycling_A_x,cycling_A_y,cycling_A_z,cycling_Gyr_x,cycling_Gyr_y,cycling_Gyr_z,cycling_freq,cycling_speed
0,0.105310,-4.346861,8.560024,1.084248,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
1,0.313140,-3.879065,8.463713,1.387837,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
2,0.520969,-2.958127,9.157033,1.877468,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
3,0.728799,-1.050449,9.868599,1.626222,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
4,0.936629,-0.005384,9.833604,1.721935,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31447,1840.968262,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739,1000.274047,0.090463,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
31448,1840.968262,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739,999.126401,-0.299974,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
31449,1840.968262,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739,997.978755,-0.690411,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
31450,1840.968262,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739,996.831110,-1.080848,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
31451,1840.968262,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739,997.622061,-0.810641,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654

In [755]:
#remove last 20000 rows
df_all = df_all.iloc[:-10000, :]
df_all

,Time (s),metro_A_x,metro_A_y,metro_A_z,metro_Gyr_x,metro_Gyr_y,metro_Gyr_z,metro_doppler_frequ,metro_doppler_speed,walking_A_x,walking_A_y,walking_A_z,walking_Gyr_x,walking_Gyr_y,walking_Gyr_z,walking_freq,walking_speed,cycling_A_x,cycling_A_y,cycling_A_z,cycling_Gyr_x,cycling_Gyr_y,cycling_Gyr_z,cycling_freq,cycling_speed
0,0.105310,-4.346861,8.560024,1.084248,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
1,0.313140,-3.879065,8.463713,1.387837,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
2,0.520969,-2.958127,9.157033,1.877468,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
3,0.728799,-1.050449,9.868599,1.626222,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
4,0.936629,-0.005384,9.833604,1.721935,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21447,1840.968262,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739,998.276453,-0.587123,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
21448,1840.968262,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739,998.327146,-0.569834,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
21449,1840.968262,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739,998.377838,-0.552545,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
21450,1840.968262,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739,998.428531,-0.535256,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
21451,1840.968262,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739,998.479224,-0.517967,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654

In [669]:
#save df_all to csv
df_all.to_csv('df_all.csv', index=False)

In [756]:
#get mean of all columns
df_all.mean()

Time (s)                870.250819
metro_A_x                 0.111194
metro_A_y                 9.047183
metro_A_z                 3.657477
metro_Gyr_x              -0.067658
metro_Gyr_y               0.039773
metro_Gyr_z              -0.029826
metro_doppler_frequ     998.209061
metro_doppler_speed      -0.610825
walking_A_x               0.035840
walking_A_y              -0.467801
walking_A_z              -0.135877
walking_Gyr_x            -0.045283
walking_Gyr_y            -0.021737
walking_Gyr_z             0.013967
walking_freq           1000.533428
walking_speed             0.179565
cycling_A_x              -4.937590
cycling_A_y               4.652843
cycling_A_z               8.306684
cycling_Gyr_x             0.058107
cycling_Gyr_y            -0.256938
cycling_Gyr_z            -0.034284
cycling_freq           1003.170769
cycling_speed             1.074654
dtype: float64

In [757]:
#describe df_all
df_all.describe()

,Time (s),metro_A_x,metro_A_y,metro_A_z,metro_Gyr_x,metro_Gyr_y,metro_Gyr_z,metro_doppler_frequ,metro_doppler_speed,walking_A_x,walking_A_y,walking_A_z,walking_Gyr_x,walking_Gyr_y,walking_Gyr_z,walking_freq,walking_speed,cycling_A_x,cycling_A_y,cycling_A_z,cycling_Gyr_x,cycling_Gyr_y,cycling_Gyr_z,cycling_freq,cycling_speed
count,30095.000000,30095.000000,30095.000000,30095.000000,30095.000000,30095.000000,30095.000000,30095.000000,30095.000000,30095.000000,30095.000000,30095.000000,30095.000000,30095.000000,30095.000000,30095.000000,30095.000000,30095.00000,30095.000000,30095.000000,30095.000000,30095.000000,30095.000000,3.009500e+04,3.009500e+04
mean,870.250819,0.111194,9.047183,3.657477,-0.067658,0.039773,-0.029826,998.209061,-0.610825,0.035840,-0.467801,-0.135877,-0.045283,-0.021737,0.013967,1000.533428,0.179565,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1.003171e+03,1.074654e+00
std,586.295153,0.181658,0.233196,0.761919,0.100227,0.074430,0.035594,1.734329,0.606882,1.702769,1.463733,1.448674,0.622602,0.712725,0.819402,1.893819,0.643700,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,5.653740e-10,2.862203e-13
min,0.105310,-4.346861,7.255637,-2.973082,-0.902756,-1.720909,-0.675902,995.280176,-3.254816,-22.497583,-24.901519,-21.007603,-9.914701,-10.884785,-8.746300,995.958423,-1.379713,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1.003171e+03,1.074654e+00
25%,384.145061,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.049143,-0.088391,0.005363,999.184944,-0.277908,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1.003171e+03,1.074654e+00
50%,651.310263,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1.003171e+03,1.074654e+00
75%,1397.275034,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,0.065907,-0.057391,-0.032393,-0.049143,0.026101,0.037881,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1.003171e+03,1.074654e+00
max,1840.968262,1.529612,11.113464,5.790332,0.684683,1.463743,1.166718,1004.943898,3.350766,31.072291,13.554321,20.860035,13.271033,9.926262,9.688485,1004.891960,1.655169,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1.003171e+03,1.074654e+00

In [758]:
#store means in dataframe
df_means_all = pd.DataFrame(df_all.mean())

In [759]:
window_size = 1000

In [760]:
col_int = ['metro_doppler_frequ',	'metro_doppler_speed', 'walking_freq', 'walking_speed', 'cycling_freq', 'cycling_speed']

In [761]:
mean_per_window = df_all[col_int].groupby(df_all.index // window_size).mean()

In [762]:
mean_per_window

,metro_doppler_frequ,metro_doppler_speed,walking_freq,walking_speed,cycling_freq,cycling_speed
0,998.673557,-0.470974,1000.782517,0.264689,1003.170769,1.074654
1,998.874912,-0.397778,1000.851129,0.287872,1003.170769,1.074654
2,998.741504,-0.431020,1000.811937,0.274496,1003.170769,1.074654
3,998.675793,-0.439194,1000.762458,0.257783,1003.170769,1.074654
4,998.914726,-0.364063,1000.884014,0.299152,1003.170769,1.074654
5,998.810937,-0.420757,1000.691038,0.233651,1003.170769,1.074654
6,998.680322,-0.444663,1000.848282,0.286919,1003.170769,1.074654
7,998.668048,-0.451993,1000.820425,0.277470,1003.170769,1.074654
8,998.374183,-0.529988,1000.757612,0.255812,1003.170769,1.074654
9,997.485809,-0.856980,1000.148554,0.048171,1003.170769,1.074654
10,997.485809,-0.856980,1000.506246,0.169908,1003.170769,1.074654
11,997.485809,-0.856980,1000.135354,0.043889,1003.170769,1.074654
12,997.485809,-0.856980,1000.061349,0.018473,1003.170769,1.074654
13,997.485809,-0.856980,1000.213355,0.070580,1003.170769,1.074654
14,997.485809,-0.856980,999.961604,-0.015456,1003.170769,1.074654
15,997.485809,-0.856980,1000.376615,0.125714,1003.170769,1.074654
16,997.485809,-0.856980,1000.199836,0.065711,1003.170769,1.074654
17,997.485809,-0.856980,999.778807,-0.077147,1003.170769,1.074654
18,997.485809,-0.856980,1000.082554,0.025578,1003.170769,1.074654
19,997.485809,-0.856980,1000.300183,0.099615,1003.170769,1.074654
20,997.485809,-0.856980,1000.375478,0.125235,1003.170769,1.074654
21,997.485809,-0.856980,999.480597,-0.178387,1003.170769,1.074654

In [763]:
#save mean_per_window in dataframe
df_means = pd.DataFrame(mean_per_window)

In [764]:
#get max value of the gyr columns
df_all[['metro_Gyr_x', 'metro_Gyr_y', 'metro_Gyr_z', 'walking_Gyr_x', 'walking_Gyr_y', 'walking_Gyr_z', 'cycling_Gyr_x', 'cycling_Gyr_y', 'cycling_Gyr_z']].max()

metro_Gyr_x       0.684683
metro_Gyr_y       1.463743
metro_Gyr_z       1.166718
walking_Gyr_x    13.271033
walking_Gyr_y     9.926262
walking_Gyr_z     9.688485
cycling_Gyr_x     0.058107
cycling_Gyr_y    -0.256938
cycling_Gyr_z    -0.034284
dtype: float64

In [765]:
#GET min value of the gyr columns
df_all[['metro_Gyr_x', 'metro_Gyr_y', 'metro_Gyr_z', 'walking_Gyr_x', 'walking_Gyr_y', 'walking_Gyr_z', 'cycling_Gyr_x', 'cycling_Gyr_y', 'cycling_Gyr_z']].min()

metro_Gyr_x      -0.902756
metro_Gyr_y      -1.720909
metro_Gyr_z      -0.675902
walking_Gyr_x    -9.914701
walking_Gyr_y   -10.884785
walking_Gyr_z    -8.746300
cycling_Gyr_x     0.058107
cycling_Gyr_y    -0.256938
cycling_Gyr_z    -0.034284
dtype: float64

In [766]:
#use windo size and get std of all columns
std_per_window = df_all.groupby(df_all.index // window_size).std()

In [767]:
std_per_window

,Time (s),metro_A_x,metro_A_y,metro_A_z,metro_Gyr_x,metro_Gyr_y,metro_Gyr_z,metro_doppler_frequ,metro_doppler_speed,walking_A_x,walking_A_y,walking_A_z,walking_Gyr_x,walking_Gyr_y,walking_Gyr_z,walking_freq,walking_speed,cycling_A_x,cycling_A_y,cycling_A_z,cycling_Gyr_x,cycling_Gyr_y,cycling_Gyr_z,cycling_freq,cycling_speed
0,59.010298,0.310925,0.400007,1.248401,0.157256,0.093025,0.047123,2.124002,0.904811,2.590707,2.167696,2.306070,0.000000,0.000000,0.000000,1.534737,0.521812,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,59.236700,0.249910,0.413356,1.432717,0.157256,0.093025,0.047123,2.207502,0.738274,2.406334,1.995327,1.733240,0.000000,0.000000,0.000000,1.679480,0.570843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,59.686015,0.539739,0.385686,1.232105,0.157256,0.093025,0.047123,2.162009,0.730559,1.931818,1.628309,2.001877,0.000000,0.000000,0.000000,1.714540,0.582771,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,304.788998,0.128754,0.150720,0.450655,0.092577,0.102510,0.050856,2.072763,0.724913,0.623564,0.607815,0.722460,0.000000,0.000000,0.000000,1.600168,0.544015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,315.003885,0.000000,0.000000,0.000000,0.034655,0.106801,0.035758,2.265378,0.766440,1.637829,1.349854,1.352024,0.000000,0.000000,0.000000,1.584269,0.538445,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,311.423586,0.000000,0.000000,0.000000,0.063675,0.121841,0.054015,2.159931,0.728299,2.264523,1.832019,1.867201,0.000000,0.000000,0.000000,1.567018,0.532882,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,332.874888,0.000000,0.000000,0.000000,0.018021,0.030290,0.020981,2.043099,0.700737,2.072802,1.932691,1.705059,0.000000,0.000000,0.000000,1.586291,0.539221,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,428.821196,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.096166,0.714112,2.379945,2.034239,1.904147,0.000000,0.000000,0.000000,1.622754,0.551721,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,516.613170,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.855001,0.646539,2.885726,2.699728,2.416019,0.000000,0.000000,0.000000,1.836407,0.623930,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,664.637178,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.486406,1.493389,1.274510,1.482587,1.317788,1.374151,2.161248,0.734447,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,57.944103,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.267708,1.416551,1.651806,2.158723,0.733405,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,57.942301,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.023112,1.194195,1.441292,2.134289,0.725388,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,57.943442,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.771318,0.755231,0.650157,2.290544,0.778354,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,57.944899,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.763687,0.731703,0.893108,2.022631,0.687167,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,57.948647,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.979916,1.415335,1.589066,2.215955,0.752995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,57.948696,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.106062,1.209570,1.568034,2.124053,0.721749,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,57.948064,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.087777,1.338176,1.586824,2.107681,0.716222,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,57.945006,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.278184,1.549806,1.823877,1.867380,0.634833,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,20.723975,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.783076,1.025131,1.207062,2.182537,0.741378,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.199860,0.747393,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.296631,0.780309,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.919231,0.652766,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [768]:
window_size_2 = 100

In [769]:
df_fourier = pd.DataFrame()

In [772]:
for i in range(0, len(df_all), window_size):
    window = df_all.iloc[i:i+window_size_2]
    window_fourier = np.abs(np.fft.fft(window))
    df_fourier = df_fourier.append(window_fourier, ignore_index=True)

/var/folders/wr/n1gn41j97w53l7jc_kv9fb9w0000gn/T/ipykernel_48264/3412161737.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_fourier = df_fourier.append(window_fourier, ignore_index=True)

TypeError: cannot concatenate object of type '<class 'numpy.ndarray'>'; only Series and DataFrame objs are valid

In [773]:
#slice df_all in widows of 100 rows
df_all_2 = df_all.iloc[::100, :]

In [774]:
df_all_2

,Time (s),metro_A_x,metro_A_y,metro_A_z,metro_Gyr_x,metro_Gyr_y,metro_Gyr_z,metro_doppler_frequ,metro_doppler_speed,walking_A_x,walking_A_y,walking_A_z,walking_Gyr_x,walking_Gyr_y,walking_Gyr_z,walking_freq,walking_speed,cycling_A_x,cycling_A_y,cycling_A_z,cycling_Gyr_x,cycling_Gyr_y,cycling_Gyr_z,cycling_freq,cycling_speed
0,0.105310,-4.346861,8.560024,1.084248,-0.353604,-0.120108,0.050013,1000.597433,0.203006,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
100,20.888497,0.997209,9.373584,3.098406,-0.353604,-0.120108,0.050013,995.455793,-1.936438,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
200,41.671836,0.071486,9.687343,1.455135,-0.353604,-0.120108,0.050013,997.986513,-2.558722,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
300,62.455194,0.237488,9.136993,3.567998,-0.353604,-0.120108,0.050013,1000.420608,0.657778,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
400,83.248466,0.208475,9.744472,1.774577,-0.353604,-0.120108,0.050013,1001.990536,1.422022,0.065907,-0.057391,-0.032393,-0.049143,-0.088391,0.005363,1001.308193,0.444204,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20957,1840.968262,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739,1002.946177,0.998097,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
21057,1840.968262,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739,997.821759,-0.744007,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
21157,1840.968262,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739,1000.248550,0.084152,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
21257,1840.968262,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739,996.464028,-1.206498,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654
21357,1840.968262,0.126820,8.972188,3.901796,-0.039171,0.065895,-0.044210,997.485809,-0.856980,-0.157216,-0.482441,-0.489857,-0.122135,0.239455,0.104739,1001.343023,0.454078,-4.93759,4.652843,8.306684,0.058107,-0.256938,-0.034284,1003.170769,1.074654

In [775]:
#apply fourier transform to df_all_2
df_fourier_2 = np.abs(np.fft.fft(df_all_2))

In [776]:
df_fourier_2

array([[3019.41005692,  146.38286609,  275.8116023 , ..., 2925.13386909,
         275.8116023 ,  146.38286609],
       [3041.08394869,  127.85944861,  258.33561713, ..., 2920.59969566,
         258.33561713,  127.85944861],
       [3061.52048703,  116.10900556,  257.06790637, ..., 2930.97707026,
         257.06790637,  116.10900556],
       ...,
       [4862.03990285, 1741.0024671 , 1775.25866891, ..., 3899.99154178,
        1775.25866891, 1741.0024671 ],
       [4856.96473132, 1744.71007224, 1775.04088226, ..., 3895.37263152,
        1775.04088226, 1744.71007224],
       [4863.50430238, 1739.93346851, 1775.32530475, ..., 3901.32421417,
        1775.32530475, 1739.93346851]])